EPMECO-15594: Transfer topic list table to asynchronous loading
epam/eco-kafka-manager pull request #55
Opened 2023-05-19 05:34 UTC by michael200kg

Transform topics filter, made button copy URL

2023-05-19 14:07 UTC, YevgeniyYP requested changes

2023-05-22 06:52 UTC, michael200kg commented on commons/src/main/java/com/epam/eco/kafkamanager/TopicListSearchCriteriaImpl.java
> +                switch (filterColumn) {
I consider this option, but, I use equals operator, that is prohibited in a lambda functions, because all of variables must be efficiently final.

2023-05-22 06:55 UTC, michael200kg commented on commons/src/main/java/com/epam/eco/kafkamanager/TopicSearchCriteria.java
> +public interface TopicSearchCriteria extends SearchCriteria<TopicInfo> {
This interface need to implement both versions of topic criteria, new one for the topic list in ui module, and to leave old version intact to use in a rest module.

2023-05-22 06:57 UTC, michael200kg commented on commons/src/main/java/com/epam/eco/kafkamanager/TopicListSearchCriteriaImpl.java
> +            if(ifKeyExists(key) && key.indexOf(OPERATION_SEPARATOR) > 0) {
if it be on a first position it means that this case doesn't fit, thus we skip it by this if clause

2023-05-22 07:33 UTC, michael200kg commented on commons/src/test/java/com/epam/eco/kafkamanager/TopicListSearchCriteriaImplTest.java
> +    private TopicListSearchCriteriaImpl criteria;
No necessity to initialize this var every test

2023-05-23 08:09 UTC, YevgeniyYP commented on commons/src/test/java/com/epam/eco/kafkamanager/TopicListSearchCriteriaImplTest.java
> +    private TopicListSearchCriteriaImpl criteria;
As I ca see, each test initializes this field for its needs. It must be local, I guess

2023-05-23 09:39 UTC, michael200kg commented on commons/src/main/java/com/epam/eco/kafkamanager/TopicListSearchCriteriaImpl.java
> +                switch (filterColumn) {
replicationStateClause = ReplicationState.valueOf((String) map.get(key)); Not allowed inside lambda

2023-05-24 07:37 UTC, YevgeniyYP approved these changes

2023-05-24 07:37 UTC, merged