Made async loading of consumer groups, new standard filter
epam/eco-kafka-manager pull request #65
Opened 2023-08-10 12:18 UTC by michael200kg

Made async loading of consumer groups, new standard filter, add faq to filter entries, refactor full screen mechanism

2023-08-11 12:01 UTC, YevgeniyYP requested changes

2023-08-11 12:34 UTC, michael200kg commented on commons/src/main/java/com/epam/eco/kafkamanager/AbstractSearchCriteriaImpl.java
> +    protected static boolean compareStringValues(String filterValue, String value, Operation operation) {
EQUAL, GREATER or LESS defined in operation parameter.

2023-08-11 14:14 UTC, YevgeniyYP commented on commons/src/main/java/com/epam/eco/kafkamanager/AbstractSearchCriteriaImpl.java
> +    protected static class ClausesWithHandler<FILTERTYPE, COLUMNTYPE, RECORDTYPE> {
The simplest solution could be:
for AbstractSearchCriteriaImpl:
```
protected final Set<ClausesWithHandler<?, ?, D>> clauses;
protected AbstractSearchCriteriaImpl(Set<ClausesWithHandler<?, ?, D>> clauses) {
     this.clauses = clauses;
}
```
for concrete Impls:
```
    private TopicListSearchCriteriaImpl(Set<ClausesWithHandler<?, ?, TopicInfo>> clauses) {
        super(clauses);
    }
```

This way, it becomes compile time error

2023-08-14 07:02 UTC, michael200kg commented on commons/src/main/java/com/epam/eco/kafkamanager/AbstractSearchCriteriaImpl.java
> +    protected static final String OPERATION_SEPARATOR = "_";
There is only a predefined list of operations. We can check it all. So I haven't see a problem here.

2023-09-21 09:18 UTC, merged