Transfer to spring-boot-3.1.2 and oauth2 authorization
epam/eco-kafka-manager pull request #75
Opened 2023-11-14 08:36 UTC by michael200kg

Transfer to a Spring boot 3 
Add OAuth2 authorization
Made some code clean up

2023-11-17 11:43 UTC, YevgeniyYP requested changes

2023-11-17 11:43 UTC, YevgeniyYP commented on ui/src/main/java/com/epam/eco/kafkamanager/ui/GlobalModelEnrichingInterceptor.java
> +        if(nonNull(SecurityContextHolder.getContext().getAuthentication())) {
Check `authentication`  variable on null instead

2023-11-17 11:43 UTC, YevgeniyYP commented on ui/src/main/java/com/epam/eco/kafkamanager/ui/GlobalModelEnrichingInterceptor.java
> +public class GlobalModelEnrichingInterceptor implements HandlerInterceptor {
Extending `WebRequestHandlerInterceptorAdapter` is not mandatory here?

2023-11-17 11:43 UTC, YevgeniyYP commented on ui/src/main/java/com/epam/eco/kafkamanager/ui/config/BaseWebSecurityConfig.java
> +public class BaseWebSecurityConfig {
Can it be abstract and `commonHttpConfig()` protected?

2023-11-17 11:43 UTC, YevgeniyYP commented on ui/src/main/java/com/epam/eco/kafkamanager/ui/config/KeycloakBaseWebSecurityConfig.java
> +                .flatMap(x -> ((Map<String, Object>) x).entrySet().stream())
Type casting looks harmful without pre-checking

2023-11-27 06:53 UTC, michael200kg commented on commons/src/test/java/com/epam/eco/kafkamanager/KafkaSchemaIdAwareAvroDeserializerTest.java
> +    private final static byte[] BYTES_SHORT = new byte[4];
just memory efficiency nothing more

2023-11-27 11:20 UTC, michael200kg commented on commons/src/test/java/com/epam/eco/kafkamanager/exec/AbstractAsyncStatefullTaskExecutorTest.java
>          private Iterator<String> iterator;
Above in the code:
iterator = phrases.iterator();

2023-11-28 10:01 UTC, YevgeniyYP approved these changes

2023-11-28 10:01 UTC, merged